services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: database
      TYPEORM_USERNAME: user
      TYPEORM_PASSWORD: password
      TYPEORM_DATABASE: postgres
      TYPEORM_PORT: 5432
      TYPEORM_SYNCHRONIZE: true
      TYPEORM_ENTITIES: .backend/src/**/*.entity.ts
    ports:
      - "4000:4000"
    depends_on:
      - database
    command: npm run start:dev

volumes:
  db_data:
