version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend  # Asegúrate de que este es el directorio correcto
      dockerfile: Dockerfile # Este es el nombre del archivo Dockerfile
    environment:
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: database
      TYPEORM_USERNAME: myuser
      TYPEORM_PASSWORD: mypassword
      TYPEORM_DATABASE: mydb
      TYPEORM_PORT: 5432
      TYPEORM_SYNCHRONIZE: true
      TYPEORM_ENTITIES: ./src/**/*.entity.ts
    ports:
      - "4000:4000"
    depends_on:
      - database
    command: npm run start:dev

volumes:
  db_data:
